# -*- coding: utf-8 -*-
"""Unfreeze top 2 layers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101GwvvoqqE20QNh1u-xmO2Yke8BmcPg_
"""

!pip install iterative-stratification -q

!pip install rdkit -q

"""
Experiment: Phase 1 Fine-tuning — ChemBERTa (top 2 layers unfrozen) + MLP head + ASL
Goal : classify the 12 metacategories and beat the BR+RF baseline (macro PR AUC 0.624)

Strategy:
  - Embeddings + layers 1-4 frozen
  - Layers 5-6 (top 2 transformer layers) unfrozen
  - MLP head trainable
  - Two learning rates: backbone (low) vs head (higher)
  - Linear warmup (10% of steps) -> cosine decay
  - On-the-fly SMILES enumeration (20-30 variants per molecule, re-sampled every epoch)
  - ASL with gamma_neg=2 (tune up to 3-4 if rare labels still lag) + label smoothing
  - Early stopping on validation macro-F1 (patience 5-10), not loss
  - Post-hoc per-label threshold calibration on validation set
"""

import os
import sys
import copy
import random
import logging
import warnings
from datetime import datetime

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, get_cosine_schedule_with_warmup
from sklearn.metrics import average_precision_score, roc_auc_score, f1_score
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from rdkit import Chem
from rdkit import RDLogger

RDLogger.DisableLog("rdApp.*")  # silence RDKit warnings on invalid SMILES
warnings.filterwarnings("ignore")

# ══ EXPERIMENT CONFIG — edit here ═══════════════════════════════
MODEL_NAME    = "seyonec/ChemBERTa-zinc-base-v1"
GPU_ID        = "cuda:0"
MAX_LEN       = 128
BATCH_SIZE    = 32                 # smaller than frozen runs — backbone now runs every batch
MAX_EPOCHS    = 100
PATIENCE      = 10                  # early stopping patience (epochs without val macro-F1 improvement)

# Two-LR setup
LR_HEAD       = 1e-4
LR_BACKBONE   = 1e-5               # safe start; can range 5e-6 to 2e-5
WEIGHT_DECAY  = 0.01
WARMUP_FRAC   = 0.10               # warmup over first 10% of total steps

# Unfreezing
N_UNFROZEN_LAYERS = 2              # top-2 transformer layers unfrozen

# SMILES enumeration
N_SMILES_VARIANTS = 20             # variants generated per molecule, resampled each epoch

# ASL hyperparameters
ASL_GAMMA_POS   = 0
ASL_GAMMA_NEG   = 4                # start at 2; raise to 3-4 if rare labels still lag
ASL_MARGIN      = 0.05
LABEL_SMOOTHING = 0.05

# Paths
DATA_PATH = "features_clustering_A_r2.csv"
LOG_DIR   = "logs"
CKPT_DIR  = "checkpoints"

META_COLS = [
    "floral", "fruity", "sweet", "woody",
    "green", "spicy", "animal_musk", "earthy",
    "citrus", "chemical", "gourmand", "powdery_amber",
]

DEBUG =False
# ═══════════════════════════════════════════════════════════════


# ── Logging ───────────────────────────────────────────────────────
def setup_logger(log_dir: str, file_name: str = None) -> logging.Logger:
    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path  = os.path.join(log_dir, f"{file_name}_{timestamp}.log" if file_name else f"experiment_{timestamp}.log")

    logger = logging.getLogger("chemberta_finetune")
    if logger.hasHandlers():
        logger.handlers.clear()
    logger.setLevel(logging.INFO)

    fmt = logging.Formatter("%(asctime)s | %(message)s", datefmt="%H:%M:%S")

    fh = logging.FileHandler(log_path)
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(fmt)
    logger.addHandler(sh)

    logger.info(f"Log file : {log_path}")
    return logger


# ── SMILES enumeration ──────────────────────────────────────────────
def enumerate_smiles(smiles: str, n_variants: int) -> list:
    """Generate up to n_variants random equivalent SMILES for one molecule.
    Falls back to the canonical/original string if RDKit fails to parse it."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return [smiles] * n_variants
    variants = set()
    attempts = 0
    while len(variants) < n_variants and attempts < n_variants * 3:
        variants.add(Chem.MolToSmiles(mol, doRandom=True, canonical=False))
        attempts += 1
    variants = list(variants)
    if not variants:
        variants = [smiles]
    # pad by repeating if RDKit produced fewer unique variants than requested
    while len(variants) < n_variants:
        variants.append(random.choice(variants))
    return variants


# ── Dataset ──────────────────────────────────────────────────────────
class SMILESDataset(Dataset):
    """
    Holds precomputed SMILES variant pools per molecule.
    Each __getitem__ call picks a fresh random variant -> on-the-fly augmentation,
    re-sampled naturally every epoch since DataLoader re-iterates the dataset.
    """
    def __init__(self, smiles_variant_pools: list, Y: np.ndarray):
        self.pools = smiles_variant_pools   # list[list[str]], one pool per molecule
        self.Y = torch.tensor(Y, dtype=torch.float32)

    def __len__(self):
        return len(self.pools)

    def __getitem__(self, idx):
        smi = random.choice(self.pools[idx])
        return smi, self.Y[idx]


def collate_fn(batch, tokenizer, max_len):
    smiles_list, labels = zip(*batch)
    tokens = tokenizer(
        list(smiles_list),
        padding=True,
        truncation=True,
        max_length=max_len,
        return_tensors="pt",
    )
    labels = torch.stack(labels)
    return tokens, labels


# ── Model ──────────────────────────────────────────────────────────
class FineTunedChemBERTa(nn.Module):
    def __init__(self, backbone: nn.Module, hidden_dim: int = 768,
                 mlp_dim: int = 256, num_labels: int = 12):
        super().__init__()
        self.backbone = backbone
        self.head = nn.Sequential(
            nn.Linear(hidden_dim, mlp_dim),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(mlp_dim, num_labels),
        )

    def forward(self, tokens):
        out = self.backbone(**tokens)
        cls = out.last_hidden_state[:, 0, :]   # [CLS] token
        return self.head(cls)


def freeze_backbone_layers(backbone: nn.Module, n_unfrozen: int, logger: logging.Logger):
    """Freeze embeddings + all but the top n_unfrozen transformer layers."""
    for p in backbone.parameters():
        p.requires_grad = False

    total_layers = len(backbone.encoder.layer)
    unfreeze_from = total_layers - n_unfrozen

    for i, layer in enumerate(backbone.encoder.layer):
        if i >= unfreeze_from:
            for p in layer.parameters():
                p.requires_grad = True

    n_trainable = sum(p.numel() for p in backbone.parameters() if p.requires_grad)
    n_total     = sum(p.numel() for p in backbone.parameters())
    logger.info(f"Backbone layers: {total_layers} total, layers "
                f"{unfreeze_from}-{total_layers - 1} unfrozen "
                f"({n_trainable:,} / {n_total:,} params trainable)")


# ── Loss: ASL + label smoothing ─────────────────────────────────────
class AsymmetricLossWithSmoothing(nn.Module):
    def __init__(self, gamma_pos=0, gamma_neg=2, margin=0.05, smoothing=0.05):
        super().__init__()
        self.gamma_pos = gamma_pos
        self.gamma_neg = gamma_neg
        self.margin    = margin
        self.smoothing = smoothing

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        # label smoothing: push hard 0/1 targets slightly toward 0.5
        targets = targets * (1 - self.smoothing) + 0.5 * self.smoothing

        probs   = torch.sigmoid(logits)
        probs_m = torch.clamp(probs - self.margin, min=0)

        loss_pos = targets       * torch.log(probs    + 1e-8) * (1 - probs)   ** self.gamma_pos
        loss_neg = (1 - targets) * torch.log(1 - probs_m + 1e-8) * probs_m   ** self.gamma_neg

        return -torch.mean(loss_pos + loss_neg)


# ── Evaluation ───────────────────────────────────────────────────────
def evaluate(model, loader, device):
    model.eval()
    all_probs, all_labels = [], []
    with torch.no_grad():
        for tokens, Y_b in loader:
            tokens = {k: v.to(device) for k, v in tokens.items()}
            logits = model(tokens)
            probs  = torch.sigmoid(logits).cpu().numpy()
            all_probs.append(probs)
            all_labels.append(Y_b.numpy())

    probs  = np.vstack(all_probs)
    labels = np.vstack(all_labels)

    valid = [i for i in range(labels.shape[1]) if labels[:, i].sum() > 0]
    pr_auc  = np.mean([average_precision_score(labels[:, i], probs[:, i]) for i in valid])
    roc_auc = np.mean([roc_auc_score(labels[:, i],           probs[:, i]) for i in valid])

    # macro-F1 at default 0.5 threshold, used only for early-stopping signal
    preds = (probs >= 0.5).astype(int)
    macro_f1 = f1_score(labels, preds, average="macro", zero_division=0)

    return pr_auc, roc_auc, macro_f1, probs, labels


def find_optimal_thresholds(probs: np.ndarray, labels: np.ndarray) -> np.ndarray:
    thresholds = np.arange(0.1, 0.9, 0.02)
    best = []
    for i in range(labels.shape[1]):
        best_t, best_f1 = 0.5, 0.0
        for t in thresholds:
            f1 = f1_score(labels[:, i], (probs[:, i] >= t).astype(int), zero_division=0)
            if f1 > best_f1:
                best_f1, best_t = f1, t
        best.append(best_t)
    return np.array(best)


# ── Main ──────────────────────────────────────────────────────────
def main():
    logger = setup_logger(LOG_DIR, "chemberta_finetune_phase1")
    device = torch.device(GPU_ID if torch.cuda.is_available() else "cpu")
    os.makedirs(CKPT_DIR, exist_ok=True)

    logger.info(f"Device   : {device}")
    logger.info(f"Model    : {MODEL_NAME}")
    logger.info(f"Config   : LR_head={LR_HEAD}, LR_backbone={LR_BACKBONE}, "
                f"BS={BATCH_SIZE}, MAX_EPOCHS={MAX_EPOCHS}, PATIENCE={PATIENCE}")
    logger.info(f"Unfreeze : top {N_UNFROZEN_LAYERS} layers")
    logger.info(f"ASL      : gamma_pos={ASL_GAMMA_POS}, gamma_neg={ASL_GAMMA_NEG}, "
                f"margin={ASL_MARGIN}, smoothing={LABEL_SMOOTHING}")
    logger.info(f"SMILES enumeration: {N_SMILES_VARIANTS} variants/molecule (train only)")

    # ── Data ──
    logger.info(f"Loading data from {DATA_PATH}")
    df = pd.read_csv(DATA_PATH, sep=";").dropna(subset=["SMILES"]).reset_index(drop=True)
    logger.info(f"Dataset  : {len(df)} molecules")
    if DEBUG:
      df = df.head(150).reset_index(drop=True)
      logger.info("DEBUG MODE: using 150 samples only")

    smiles = df["SMILES"].tolist()
    Y = df[META_COLS].values.astype(np.float32)

    # ── Splits (stratified) ──
    msss = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    idx = np.arange(len(smiles))
    for tv_idx, test_idx in msss.split(idx, Y):
        pass

    msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.15, random_state=42)
    for tr_idx, val_idx in msss2.split(tv_idx, Y[tv_idx]):
        train_idx = tv_idx[tr_idx]
        val_idx   = tv_idx[val_idx]

    logger.info(f"Train: {len(train_idx)} | Val: {len(val_idx)} | Test: {len(test_idx)}")

    # ── Pre-generate SMILES variant pools (train set only gets augmentation) ──
    logger.info("Generating SMILES enumeration pools for training set...")
    train_pools = [enumerate_smiles(smiles[i], N_SMILES_VARIANTS) for i in train_idx]
    val_pools   = [[smiles[i]] for i in val_idx]    # canonical only, no augmentation
    test_pools  = [[smiles[i]] for i in test_idx]   # canonical only, no augmentation

    Y_train, Y_val, Y_test = Y[train_idx], Y[val_idx], Y[test_idx]

    # ── Tokenizer + model ──
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    backbone  = AutoModel.from_pretrained(MODEL_NAME)
    freeze_backbone_layers(backbone, N_UNFROZEN_LAYERS, logger)

    model = FineTunedChemBERTa(backbone, hidden_dim=768, mlp_dim=256, num_labels=12).to(device)

    # ── Datasets / loaders ──
    train_ds = SMILESDataset(train_pools, Y_train)
    val_ds   = SMILESDataset(val_pools,   Y_val)
    test_ds  = SMILESDataset(test_pools,  Y_test)

    collate = lambda batch: collate_fn(batch, tokenizer, MAX_LEN)
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  collate_fn=collate)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate)

    # ── Optimizer: two param groups, two LRs ──
    backbone_trainable = [p for p in model.backbone.parameters() if p.requires_grad]
    head_params         = list(model.head.parameters())

    optimizer = torch.optim.AdamW([
        {"params": backbone_trainable, "lr": LR_BACKBONE},
        {"params": head_params,        "lr": LR_HEAD},
    ], weight_decay=WEIGHT_DECAY)

    total_steps  = len(train_loader) * MAX_EPOCHS
    warmup_steps = int(total_steps * WARMUP_FRAC)
    scheduler = get_cosine_schedule_with_warmup(
        optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_steps
    )

    criterion = AsymmetricLossWithSmoothing(
        ASL_GAMMA_POS, ASL_GAMMA_NEG, ASL_MARGIN, LABEL_SMOOTHING
    )

    # ── Training loop with early stopping on val macro-F1 ──
    best_val_pr   = -1.0
    best_state    = None
    epochs_no_improve = 0

    for epoch in range(1, MAX_EPOCHS + 1):
        model.train()
        epoch_loss = 0.0
        for tokens, Y_b in train_loader:
            tokens = {k: v.to(device) for k, v in tokens.items()}
            Y_b    = Y_b.to(device)

            optimizer.zero_grad()
            logits = model(tokens)
            loss   = criterion(logits, Y_b)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            scheduler.step()
            epoch_loss += loss.item()

        val_pr, val_roc, val_f1, _, _ = evaluate(model, val_loader, device)

        improved =val_pr > best_val_pr
        if improved:
            best_val_pr = val_pr
            best_state  = copy.deepcopy(model.state_dict())
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1

        logger.info(f"Epoch {epoch:3d}/{MAX_EPOCHS} | "
                    f"Loss: {epoch_loss / len(train_loader):.4f} | "
                    f"Val PR AUC: {val_pr:.4f} | Val ROC AUC: {val_roc:.4f} | "
                    f"Val macro-F1: {val_f1:.4f}" +
                    ("  <- best" if improved else f"  (no improve {epochs_no_improve}/{PATIENCE})"))

        if epochs_no_improve >= PATIENCE:
            logger.info(f"Early stopping at epoch {epoch} (no val macro-F1 "
                        f"improvement for {PATIENCE} epochs)")
            break

    logger.info(f"Best val macro-pr: {best_val_pr:.4f}")

    # ── Save checkpoint ──
    ckpt_path = os.path.join(CKPT_DIR, "chemberta_finetune_phase1_best.pt")
    torch.save(best_state, ckpt_path)
    logger.info(f"Checkpoint saved: {ckpt_path}")

    # ── Test evaluation with threshold calibration ──
    model.load_state_dict(best_state)

    _, _, _, val_probs, val_labels = evaluate(model, val_loader, device)
    thresholds = find_optimal_thresholds(val_probs, val_labels)
    logger.info(f"Calibrated thresholds: {thresholds.round(2)}")

    test_pr, test_roc, _, test_probs, test_labels = evaluate(model, test_loader, device)
    test_preds = (test_probs >= thresholds).astype(int)
    test_f1    = f1_score(test_labels, test_preds, average="macro", zero_division=0)

    logger.info("══ Test Results — Phase 1 Fine-tuning ═══════════════")
    logger.info(f"  Macro PR AUC  : {test_pr:.4f}   (BR+RF baseline: 0.624)")
    logger.info(f"  Macro ROC AUC : {test_roc:.4f}  (BR+RF baseline: 0.820)")
    logger.info(f"  Macro F1      : {test_f1:.4f}   (BR+RF baseline: 0.567)")
    logger.info("  Per-label PR AUC:")
    for i, col in enumerate(META_COLS):
        pa = average_precision_score(test_labels[:, i], test_probs[:, i])
        logger.info(f"    {col:<25s}: {pa:.4f}")


if __name__ == "__main__":
    main()

